{% set name = "Orange3-Timeseries" %}
{% set version = "0.3.0" %}
{% set sha256 = "66ddbd9569ab661ec8c5b14a7b607813f53bac5a7e32b6c03ce3d193ca8ecd96" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - skip-symlinking-datasets.patch

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - orange3
    - statsmodels >=0.6.1
    - pandas
    - numpy
    - scipy >=0.17

test:
  imports:
    - orangecontrib.timeseries

about:
  home: https://github.com/biolab/orange3-timeseries
  license: CC-BY-NC-3.0
  summary: 'Orange3 add-on for exploring time series and sequential data.'
  license_family: Other
  doc_url: http://orange3-timeseries.readthedocs.io
  dev_url: https://github.com/biolab/orange3-timeseries

extra:
  recipe-maintainers:
    - astaric
    - kernc
