travis:
  secure:
    BINSTAR_TOKEN: U36OhElCrhj+E5tD7w3qHHzpIuuSZTsnV5BWfgdHKKix8RZlUlj8xIVJslPvNgWq9l2saccjmgJhLo4TIpv8v+CE/AJhwceqezLxdzkEydkC2ekvwGkeM53l7MsLARafPZfPjNHXpEze74j0CYRTeNwQ9HXWCSpTa5Mlz752vr6L4A0Gu+pzt6Jk/h3RDoc8o40xCjF7fv/7zPhGu3wB8DOvnJ1YDBx/58vmgBTPYiTOAvB0DnxTDx78IyRh3jP3Boi8TL/4FNi7tHmpOpN4JjV6pVnv5NBZlfNLEBUfjIjbAkBACdY5NONLZON/juKGhhTX5VccJHAx18NJwxjbzeHDilLIDPjV87Vu4STU31dXb23BqK9RlXN+gsvIjI5O/xqwLWRA/l93RTrhpqMaGJJBSW5OO43KSMXBpsdzDEfBZNa3CHaLq1XrMPicd8NnotIPj4suSuGqF+cx6nlCV/6weuB7QnriXn6ek8DMClEsoERULDF1SadeVUP/CH2hmol1ERpayT5qielvDaTzX/nQPl8D7A4RvNvQhv0OLplD4KGDbQNfI5DGM1c7R9r8pF309v3iMPS94mrknLRROPYtoTpHt1sfRLg1UZycCZqmXBq4WB/IyJ8qOrL9N3GJoxSbZ8n6wqlfrh3xtcfRQeQc99I3ANSvcoKL+3C7huI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
